descriptions = {
"Steppe Lancer": "Light cavalry unit with increased attack range. Strong in groups. Weak vs. Camel Riders and archers. Upgrades: attack, armor (Blacksmith); speed, hit points (Stable); creation speed, to Elite Steppe Lancer 900F, 550G (Stable); more resistant to Monks (Monastery).",
"Elite Steppe Lancer": "Light cavalry unit with increased attack range. Strong in groups. Weak vs. Camel Riders and archers. Upgrades: attack, armor (Blacksmith); speed, hit points (Stable); creation speed (Castle); more resistant to Monks (Monastery).",
"Xolotl Warrior": "Mesoamerican cavalry unit. Strong vs. infantry and siege. Weak vs. Pikemen and Camel Riders.  Upgrades: attack (Blacksmith); creation speed (Castle); more resistant to Monks (Monastery).",
"Knight": "Powerful all-purpose cavalry. Strong vs. infantry and archers. Weak vs. Pikemen, Camel Riders, and Monks. Upgrades: attack, armor (Blacksmith); speed, hit points, to Cavalier 300F, 300G (Stable); creation speed (Castle); more resistant to Monks (Monastery).",
"Cavalier": "Powerful all-purpose cavalry. Strong vs. infantry and archers. Weak vs. Pikemen, Camel Riders, and Monks. Upgrades: attack, armor (Blacksmith); speed, hit points, to Paladin 1300F, 750G (Stable); creation speed (Castle); more resistant to Monks (Monastery).",
"Spearman": "Anti-cavalry infantry unit. Strong vs. mounted units, especially elephants. Weak vs. archers and infantry. Upgrades: attack, armor (Blacksmith); speed, to Pikeman 215F, 90G (Barracks); creation speed (Castle); more resistant to Monks (Monastery).",
"Militia": "All-purpose infantry unit. Strong vs. buildings and infantry. Weak vs. archers at long range. Upgrades: attack, armor (Blacksmith); cost, speed, to Man-at-Arms 100F, 40G (Barracks); creation speed (Castle); more resistant to Monks (Monastery).",
"Man-at-Arms": "All-purpose infantry unit. Strong vs. buildings and infantry. Weak vs. archers at long range. Upgrades: attack, armor (Blacksmith); cost, speed, to Long Swordsman 150F, 65G (Barracks); creation speed (Castle); more resistant to Monks (Monastery).",
"Long Swordsman": "All-purpose infantry unit. Strong vs. buildings and infantry. Weak vs. archers at long range. Upgrades: attack, armor (Blacksmith); cost, speed, to Two-Handed Swordsman 300F, 100G (Barracks); creation speed (Castle); more resistant to Monks (Monastery).",
"Archer": "Ranged unit. Strong vs. units at long range. Weak vs. Skirmishers and units at close range. Upgrades: attack, range, armor (Blacksmith); attack, accuracy (University); accuracy, to Crossbowman 125F, 75G (Archery Range); creation speed (Castle); more resistant to Monks (Monastery).",
"Crossbowman": "Ranged unit. Strong vs. units at long range. Weak vs. Elite Skirmishers, Mangonels, and units at close range. Upgrades: attack, range, armor (Blacksmith); attack, accuracy (University); accuracy, to Arbalester 350F, 300G (Archery Range); creation speed (Castle); more resistant to Monks (Monastery).",
"Cavalry Archer": "Mounted archer. Strong vs. slow units at long range. Weak vs. Elite Skirmishers and units at close range. Upgrades: speed, hit points (Stable); attack, range, armor (Blacksmith); attack, accuracy (University); accuracy, armor, to Heavy Cavalry Archer 900F, 500G (Archery Range); creation speed (Castle); more resistant to Monks (Monastery).",
"Hand Cannoneer": "Gunpowder unit with powerful attack, but inaccurate at long range. Strong vs. infantry. Weak vs. Elite Skirmishers and archers. Upgrades: armor (Blacksmith); creation speed (Castle); more resistant to Monks (Monastery).",
"Elite Skirmisher": "Ranged anti-archer unit that cannot attack at close range. Strong vs. archers. Weak vs. units at close range. Upgrades: attack, range, armor (Blacksmith); attack, accuracy (University); accuracy, to Imperial Skirmisher 300W, 450G (Archery Range); creation speed (Castle); more resistant to Monks (Monastery).",
"Skirmisher": "Ranged anti-archer unit that cannot attack at close range. Strong vs. archers. Weak vs. units at close range. Upgrades: attack, range, armor (Blacksmith); attack, accuracy (University); accuracy, to Elite Skirmisher 230W, 130G (Archery Range); creation speed (Castle); more resistant to Monks (Monastery).",
"Trade Cog": "Trade unit used for generating gold at another player's Dock. To trade, click the Trade Cog then right-click another player's Dock. Will return with gold to your Dock. Upgrades: generate more gold (Market); armor, cost (Dock); more resistant to Monks (Monastery).",
"Fishing Ship": "Gathers food from fish and Fish Traps. Builds Fish Traps. Upgrades: armor, cost, speed, efficiency (Dock); more resistant to Monks (Monastery).",
"War Galley": "All-purpose warship with ranged attack. Weak vs. Fire Ships. Upgrades: armor, cost, speed, to Galleon 400F, 315W (Dock); attack, range (Blacksmith); attack, accuracy (University); more resistant to Monks (Monastery).",
"Bombard Cannon": "Siege weapon with long range. Strong vs. buildings and siege weapons. Weak vs. melee units. Upgrades: attack, range (University); to Houfnice 950F, 750G (Siege Workshop); more resistant to Monks (Monastery).",
"Battering Ram": "Anti-building siege weapon. Resistant to most ranged attacks. Garrisoned infantry increase speed and attack. Upgrades: attack (University); to Capped Ram 300F (Siege Workshop); more resistant to Monks (Monastery).",
"Mangonel": "Ranged siege weapon with area of effect attack, but cannot attack enemies at close range. Strong vs. tight groups of units. Can attack ground. Upgrades: attack, range (University); to Onager 800F, 500G (Siege Workshop); more resistant to Monks (Monastery).",
"Scorpion": "Anti-unit siege weapon. Fires bolts that pierce multiple units. Strong vs. large groups of units. Weak vs. cavalry and siege weapons. Upgrades: range, attack (University); to Heavy Scorpion 1000F, 1100W (Siege Workshop); more resistant to Monks (Monastery).",
"Trebuchet": "Powerful anti-building siege weapon with long range. Must be packed to move, unpacked to attack. Cannot attack enemies at close range. Strong vs. buildings. Can attack ground and destroy trees. Upgrades: attack, range (University); creation speed (Castle); more resistant to Monks (Monastery).",
"Monk": "Converts enemy units to your civilization. Heals friendly units (except ships and siege weapons). Strong vs. slow and non-ranged units. Weak vs. Light Cavalry and ranged units. Can collect Relics and bring them to Monasteries. Upgrades: at Monastery.",
"Trade Cart": "Trade unit used for generating gold at another player's Market. To trade, click the Trade Cart then right-click another player's Market. Will return with gold to your Market. Upgrades: generate more gold (Market); more resistant to Monks (Monastery).",
"Cataphract": "Byzantine unique cavalry unit. Strong vs. infantry. Weak vs. archers.  Upgrades: attack, armor (Blacksmith); speed, hit points (Stable); creation speed, to Elite Cataphract 1200F, 800G (Castle); more resistant to Monks.",
"Chu Ko Nu": "Chinese unique archer with rapid-fire attack. Strong vs. infantry. Weak vs. archers and siege weapons.  Upgrades: attack, range (Blacksmith); accuracy (Archery Range); attack, accuracy (University); creation speed, to Elite Chu Ko Nu 760F, 760G (Castle); more resistant to Monks (Monastery).",
"Mameluke": "Saracen unique camel unit with ranged melee attack. Strong vs. cavalry. Weak vs. archers and Pikemen.  Upgrades: attack, armor (Blacksmith); speed, hit points  (Stable); creation speed, to Elite Mameluke 600F, 500G (Castle); more resistant to Monks (Monastery).",
"Huskarl": "Gothic unique infantry unit with high pierce armor. Strong vs. archers and buildings. Weak vs. cavalry.  Upgrades: attack, armor (Blacksmith); speed (Barracks); creation speed, to Elite Huskarl 1200F, 550G (Castle); more resistant to Monks (Monastery).",
"Janissary": "Turkish unique hand cannoneer with longer range and no minimum range. Strong vs. infantry. Weak vs. archers. Upgrades: armor (Blacksmith); creation speed, to Elite Janissary 850F, 750G (Castle); more resistant to Monks (Monastery).",
"Longboat": "Viking unique ship that fires multiple arrows. Strong vs. War Galleys, land units, and buildings.  Upgrades: armor, cost, speed, to Elite Longboat 750F, 475G (Dock); attack, range (Blacksmith); attack, accuracy (University); more resistant to Monks (Monastery).",
"Longbowman": "British unique archer with very long range. Strong vs. infantry. Weak vs. cavalry and Skirmishers.  Upgrades: attack, range, armor (Blacksmith); attack, accuracy (University); creation speed, to Elite Longbowman 850F, 850G (Castle); more resistant to Monks (Monastery).",
"Mangudai": "Mongol unique cavalry archer with fast-firing attack. Strong vs. siege weapons and infantry. Weak vs. Skirmishers, Pikemen, and Camel Riders.  Upgrades: attack, range, armor (Blacksmith); speed, hit points (Stable); accuracy, armor (Archery Range); attack, accuracy (University); creation speed, to Elite Mangudai 1100F, 675G (Castle); more resistant to Monks (Monastery).",
"War Elephant": "Persian unique unit. Slow and powerful cavalry. Strong vs. buildings and units at close range. Weak vs. Monks.  Upgrades: attack, armor (Blacksmith); speed, hit points  (Stable); creation speed, to Elite War Elephant 1600F, 1200G (Castle); more resistant to Monks (Monastery).",
"Samurai": "Japanese unique infantry unit with fast attack. Strong vs. unique units and infantry. Weak vs. archers.  Upgrades: attack, armor (Blacksmith); speed (Barracks); creation speed, to Elite Samurai 750F, 650G (Castle); more resistant to Monks (Monastery).",
"Throwing Axeman": "Frankish unique infantry unit with ranged melee attack. Strong vs. infantry. Weak vs. archers and siege weapons.  Upgrades: attack, armor (Blacksmith); speed (Barracks); creation speed, to Elite Throwing Axeman 1000F, 750G (Castle); more resistant to Monks (Monastery).",
"Teutonic Knight": "Teutonic unique infantry unit. Slow and powerful. Strong vs. melee units. Weak vs. archers and Scorpions.  Upgrades: attack, armor (Blacksmith); speed (Barracks); creation speed, to Elite Teutonic Knight 950F, 500G (Castle); more resistant to Monks (Monastery).",
"Woad Raider": "Celtic unique infantry unit. Fast-moving. Strong vs. infantry and siege weapons. Weak vs. archers and cavalry.  Upgrades: attack, armor (Blacksmith); speed (Barracks); creation speed, to Elite Woad Raider 1000F, 800G (Castle); more resistant to Monks (Monastery).",
"Condottiero": "Fast anti-gunpowder infantry. Strong vs. gunpowder units. Weak vs. cavalry and archers. Trainable by Italians and their allies. Upgrades: attack, armor (Blacksmith); speed (Barracks); creation speed (Castle); more resistant to Monks (Monastery).",
"Villager": "Gathers resources. Builds and repairs buildings. Also repairs ships and siege weapons. Upgrades: hit points, armor, efficiency (Town Center); wood resource-gathering (Lumber Camp); stone, gold resource-gathering (Mining Camp); build speed (University); attack (Castle); more resistant to Monks (Monastery).",
"Archery Range": "Used to train and upgrade archer units.  Upgrades: production speed (Castle); line of sight (Town Center); hit points, armor (University); more resistant to Monks (Monastery).",
"Organ Gun": "Portuguese unique siege unit. Fires a volley of bullets. Strong vs. large groups of units. Weak vs. cavalry and Mangonels. Upgrades: attack, range (University); creation speed, to Elite Organ Gun 1200F, 500G (Castle); more resistant to Monks (Monastery).",
"Elite Organ Gun": "Portuguese unique siege unit. Fires a volley of bullets. Strong vs. large groups of units. Weak vs. cavalry and Mangonels. Upgrades: attack, range (University); creation speed (Castle); more resistant to Monks (Monastery).",
"Blacksmith": "Used to research technologies to improve armor and attack of units. Required for Siege Workshop. Upgrades: line of sight (Town Center); hit points, armor (University); more resistant to Monks (Monastery).",
"Caravel": "Portuguese unique ship that fires bolts that pierce multiple units. Strong vs. large groups of ships. Weak vs. Fire Ships. Upgrades: armor, cost, speed, to Elite Caravel 750F, 475G (Dock); attack, range (Blacksmith); attack, accuracy (University); more resistant to Monks (Monastery).",
"Elite Caravel": "Portuguese unique ship that fires bolts that pierce multiple units. Strong vs. large groups of ships. Weak vs. Fire Ships. Upgrades: armor, speed, cost (Dock); attack, range (Blacksmith); attack, accuracy (University); more resistant to Monks (Monastery).",
"Camel Archer": "Berber unique mounted archer. Strong vs. Cavalry Archers and infantry. Weak vs. Pikemen, Skirmishers, and Camel Riders. Upgrades: attack, range, armor (Blacksmith); speed, hit points (Stable); accuracy, armor (Archery Range); attack, accuracy (University); creation speed, to Elite Camel Archer 1000W, 500G (Castle); more resistant to Monks (Monastery).",
"Barracks": "Used to train and upgrade infantry units. Required for Archery Range, Stable.  Upgrades: production speed (Castle); line of sight (Town Center); hit points, armor (University); more resistant to Monks (Monastery). ",
"Elite Camel Archer": "Berber unique mounted archer. Strong vs. Cavalry Archers and infantry. Weak vs. Pikemen, Skirmishers, and Camel Riders. Upgrades: attack, armor (Blacksmith); speed, hit points (Stable); accuracy, armor (Archery Range); attack, accuracy (University); creation speed (Castle); more resistant to Monks (Monastery).",
"Genitour": "Mounted skirmisher. Strong vs. archers. Weak vs. units at close range. Trainable by Berbers and their allies. Upgrades: speed, hit points (Stable); attack, range, armor (Blacksmith); attack, accuracy (University); accuracy, to Elite Genitour 500F, 450W (Archery Range); creation speed (Castle); more resistant to Monks (Monastery).",
"Monastery": "Used to train and upgrade Monks. Garrison relics to generate gold. Cannot be converted by enemy Monks. Upgrades: line of sight (Town Center); hit points, armor (University). ",
"Elite Genitour": "Mounted skirmisher. Strong vs. archers. Weak vs. units at close range. Trainable by Berbers and their allies. Upgrades: speed, hit points (Stable); attack, range, armor (Blacksmith); attack, accuracy (University); accuracy (Archery Range); creation speed (Castle); more resistant to Monks (Monastery).",
"Gbeto": "Malian unique infantry unit with ranged melee attack. Fast-moving. Strong vs. infantry. Weak vs. archers and siege weapons. Upgrades: armor (Blacksmith); creation speed, to Elite Gbeto 900F, 600G (Castle); more resistant to Monks (Monastery).",
"Elite Gbeto": "Malian unique infantry unit with ranged melee attack. Fast-moving. Strong vs. infantry. Weak vs. archers and siege weapons. Upgrades: armor (Blacksmith); creation speed (Castle); more resistant to Monks (Monastery).",
"Castle": "Used to train and upgrade your unique unit, build Trebuchets, and research technologies. Automatically attacks enemies within range. Units can garrison inside for protection. Ranged Units and Villagers provide additional projectiles. Provides 20 population. Cannot be converted by enemy Monks. Upgrades: production speed (Castle); line of sight (Town Center); hit points, armor, accuracy (University); attack, range (Blacksmith); attack, range (Castle). ",
"Shotel Warrior": "Ethiopian unique infantry with high attack and fast training speed. Fast-moving. Strong vs. infantry. Weak vs. archers. Upgrades: attack, armor (Blacksmith); speed (Barracks); creation speed, to Elite Shotel Warrior 900F, 450G (Castle); more resistant to Monks (Monastery).",
"Dock": "Used to build and upgrade ships, deposit food from Fishing Ships, and trade with other players by sea. Upgrades: line of sight (Town Center); hit points, armor (University); more resistant to Monks (Monastery). ",
"Elite Shotel Warrior": "Ethiopian unique infantry with high attack and fast training speed. Fast-moving. Strong vs. infantry. Weak vs. archers. Upgrades: attack, armor (Blacksmith); speed (Barracks); creation speed (Castle); more resistant to Monks (Monastery).",
"Ballista Elephant": "Khmer unique elephant equipped with a Scorpion. Can destroy trees. Strong vs. infantry and archers. Weak vs. cavalry and siege weapons. Upgrades: armor (Blacksmith); speed, hit points (Stable); attack, range (University); creation speed, to Elite Ballista Elephant 1000F, 500G (Castle); more resistant to Monks (Monastery).",
"Elite Ballista Elephant": "Khmer unique elephant equipped with a Scorpion. Can destroy trees. Strong vs. infantry and archers. Weak vs. cavalry and siege weapons. Upgrades: armor (Blacksmith); speed, hit points (Stable); attack, range (University); creation speed (Castle); more resistant to Monks (Monastery).",
"Karambit Warrior": "Malay unique infantry unit. Cheap and only takes half a population unit. Strong in high numbers. Weak vs. cavalry and archers. Upgrades: attack, armor (Blacksmith); speed (Barracks); creation speed, to Elite Karambit Warrior 900F, 600G (Castle); more resistant to Monks (Monastery).",
"Farm": "Renewable food source. Provides a limited amount of food before it goes fallow and must be rebuilt. Only one Villager may work a Farm at a time. You can farm abandoned enemy Farms. Cannot be converted by enemy Monks. Upgrades: food (Mill); hit points (University).",
"Elite Karambit Warrior": "Malay unique infantry unit. Cheap and only takes half a population unit. Strong in high numbers. Weak vs. cavalry and archers. Upgrades: attack, armor (Blacksmith); speed (Barracks); creation speed (Castle); more resistant to Monks (Monastery).",
"Arambai": "Burmese unique cavalry archer with a powerful but inaccurate dart attack. Strong vs. infantry and cavalry. Weak vs. archers. Upgrades: armor (Blacksmith); speed, hit points (Stable); accuracy (University); creation speed, to Elite Arambai 1100F, 675G (Castle); more resistant to Monks (Monastery).",
"Elite Arambai": "Burmese unique cavalry archer with a powerful but inaccurate dart attack. Strong vs. infantry and cavalry. Weak vs. archers. Upgrades: armor (Blacksmith); speed, hit points (Stable); accuracy (University); creation speed (Castle); more resistant to Monks (Monastery).",
"Guard Tower": "Tower with a ranged attack. Units can garrison inside for protection. Ranged Units and Villagers shoot additional projectiles. Strong vs. archers. Weak vs.units at close range, especially Rams. Upgrades: line of sight (Town Center); attack, range (Blacksmith); attack, hit points, armor, ship attack; to Keep 500F, 350W (University).",
"Keep": "Tower with a ranged attack. Units can garrison inside for protection. Ranged Units and Villagers shoot additional projectiles. Strong vs. archers. Weak vs.units at close range, especially Rams. Upgrades: line of sight (Town Center); attack, range (Blacksmith); attack, hit points, armor, ship attack (University).",
"Bombard Tower": "Gunpowder tower with a powerful ranged attack. Units can garrison inside for protection. Strong vs. ships. Upgrades: line of sight (Town Center); attack, range (Blacksmith); hit points, armor, ship attack (University).",
"Mill": "Used to deposit food and research farming technologies. Build near forage bushes or other source of food to gather food faster. Required for Farm, Market.Upgrades: line of sight (Town Center); hit points, armor (University); more resistant to Monks (Monastery).",
"Feitoria": "Economic building. Generates resources without the need for villagers. Unique building of the Portuguese. Requires 20 population. Upgrades: line of sight (Town Center); hit points, armor (University).",
"Fire Galley": "Warship that spews fire at close range. Strong vs. Galleys. Weak vs. Demolition Rafts. Upgrades: armor, speed, cost, to Fire Ship 230F, 100G (Dock); more resistant to Monks (Monastery).",
"Market": "Used to buy and sell resources, trade with other players by land, and research trade technologies. Required to send resources to other players. Enables you to see the line of sight of your allies. Upgrades: line of sight (Town Center); hit points, armor (University); more resistant to Monks (Monastery).",
"Demolition Raft": "Demolition ship armed with explosives. Strong vs. Fire Galleys and buildings. Self-destructs when used. Upgrades: armor, speed, cost, to Demolition Ship 230F, 100G (Dock); more resistant to Monks (Monastery).",
"Town Center": "Used to train Villagers, deposit resources, advance to the next Age, and research technologies. Units can garrison inside for protection. Ranged Units and Villagers provide additional projectiles. Provides 5 population. Cannot be converted by enemy Monks. Upgrades: line of sight (Town Center); hit points, armor, accuracy (University); attack (Blacksmith).",
"Rattan Archer": "Vietnamese unique archer with high pierce armor. Strong vs. archers and infantry. Weak vs. cavalry and Skirmishers. Upgrades: attack, range, armor (Blacksmith); accuracy, armor (Archery Range); attack, accuracy (University); creation speed, to Elite Rattan Archer 1000F, 750G (Castle); more resistant to Monks (Monastery).",
"Elite Rattan Archer": "Vietnamese unique archer with high pierce armor. Strong vs. archers and infantry. Weak vs. cavalry and Skirmishers. Upgrades: attack, range, armor (Blacksmith); accuracy, armor (Archery Range); attack, accuracy (University); creation speed (Castle); more resistant to Monks (Monastery).",
"Battle Elephant": "Slow and heavy cavalry. Strong vs. cavalry, infantry, and archers. Weak vs. Monks and Pikemen. Upgrades: attack, armor (Blacksmith); speed, hit points, to Elite Battle Elephant 1200F, 900G (Stable); creation speed (Castle); more resistant to Monks (Monastery).",
"Elite Battle Elephant": "Slow and heavy cavalry. Strong vs. cavalry, infantry, and archers. Weak vs. Monks and Pikemen. Upgrades: attack, armor (Blacksmith); speed, hit points (Stable); creation speed (Castle); more resistant to Monks (Monastery).",
"Siege Workshop": "Used to build and upgrade siege weapons. Upgrades: line of sight (Town Center); hit points, armor (University); more resistant to Monks (Monastery).",
"Stable": "Used to train and upgrade cavalry units. Upgrades: production speed (Castle); line of sight (Town Center); hit points, armor (University); more resistant to Monks (Monastery).",
"University": "Used to research technologies to improve units and buildings. Upgrades: line of sight (Town Center); hit points, armor (University); more resistant to Monks (Monastery).",
"Watch Tower": "Tower with a ranged attack. Units can garrison inside for protection. Ranged Units and Villagers shoot additional projectiles. Strong vs. archers. Weak vs.units at close range, especially Rams. Upgrades: line of sight (Town Center); attack, range (Blacksmith); attack, hit points, armor, ship attack; to Guard Tower 100F, 250W (University).",
"Wonder": "A Wonder of the World that demonstrates the superiority of your civilization. Constructing a Wonder that stands for a certain period of time is one way to win the game. Cannot be converted by enemy Monks.",
"Gate": "Can be built into existing walls to allow movement of friendly units. Can be locked and unlocked. Cannot be converted by enemy Monks. Upgrades: line of sight (Town Center); hit points, armor. Researching Fortified Wall (University) increases gate hit points.",
"Palisade Gate": "Can be built into existing walls to allow movement of friendly units. Can be locked and unlocked. Cannot be converted by enemy Monks. Upgrades: line of sight (Town Center); hit points, armor (university).",
"Imperial Skirmisher": "Ranged anti-archer unit that cannot attack at close range. Strong vs. archers. Weak vs. units at close range. Trainable by Vietnamese and their allies. Upgrades: attack, range, armor (Blacksmith); attack, accuracy (University); accuracy (Archery Range); creation speed (Castle); more resistant to Monks (Monastery).",
"Palisade Wall" : "Wooden wall that is cheap and easy to build. Slows down your enemies and warns you of their approach. Cannot be converted by enemy Monks. Upgrades: line of sight (Town Center); hit points, armor (University).",
"Stone Wall" : "Stone wall that is difficult to breach without siege weapons. Slows down your enemies and warns you of their approach. Cannot be converted by enemy Monks. Upgrades: line of sight (Town Center); hit points, armor, to Fortified Wall 200F, 100W (University).",
"Fortified Wall" : "Stone wall that is difficult to breach without siege weapons. Slows down your enemies and warns you of their approach. Cannot be converted by enemy Monks. Upgrades: line of sight (Town Center); hit points, armor (University).",
"Cannon Galleon" : "Anti-building siege warship with long range, but cannot attack enemies at close range. Strong vs. buildings. Weak vs. other units. Upgrades: armor, cost, speed, to Elite Cannon Galleon 525W, 500G (Dock); more resistant to Monks (Monastery).",
"Konnik" : "Bulgarian unique cavalry unit that fights on as infantry when felled. Strong vs. infantry and archers. Weak vs. Camel Riders and Monks. Upgrades: attack, armor (Blacksmith); speed, hit points (Stable); creation speed, to Elite Konnik 1000F, 750G (Castle); more resistant to Monks (Monastery).",
"Capped Ram" : "Anti-building siege weapon. Resistant to most ranged attacks. Garrisoned infantry increase speed and attack. Upgrades: attack (University); to Siege Ram 1000F (Siege Workshop); more resistant to Monks (Monastery).",
"Elite Konnik" : "Bulgarian unique cavalry unit that fights on as infantry when felled. Strong vs. infantry and archers. Weak vs. Camel Riders and Monks. Upgrades: attack, armor (Blacksmith); speed, hit points (Stable); creation speed (Castle); more resistant to Monks (Monastery).",
"Galleon" : "All-purpose warship with ranged attack. Weak vs. Fire Ships. Upgrades: armor, cost, speed (Dock); attack, range (Blacksmith); attack, accuracy (University); more resistant to Monks (Monastery).",
"Keshik" : "Tatar unique cavalry unit that generates gold when fighting other units. Upgrades: attack, armor (Blacksmith); speed, hit points (Stable); creation speed, to Elite Keshik 700F, 900G (Castle); more resistant to Monks (Monastery).",
"Elite Keshik" : "Tatar unique cavalry unit that generates gold when fighting other units. Upgrades: attack, armor (Blacksmith); speed, hit points (Stable); creation speed (Castle); more resistant to Monks (Monastery).",
"Kipchak" : "Cuman unique cavalry archer with rapid-fire attack. Strong vs. infantry. Weak vs. Skirmishers. Upgrades: attack, range, armor (Blacksmith); speed, hit points (Stable); accuracy, armor (Archery Range); attack, accuracy (University); creation speed, to Elite Kipchak 1100F, 1000W (Castle); more resistant to Monks (Monastery).",
"Scout Cavalry" : "Fast cavalry for scouting and raiding. Resistant to conversion. Strong vs. Monks. Weak vs. Pikemen and Camel Riders. Upgrades: attack, armor (Blacksmith); speed, hit points, to Light Cavalry 150F, 50G (Stable); creation speed (Castle); more resistant to Monks (Monastery).",
"Elite Kipchak" : "Cuman unique cavalry archer with rapid-fire attack. Strong vs. infantry. Weak vs. Skirmishers. Upgrades: attack, range, armor (Blacksmith); speed, hit points (Stable); accuracy, armor (Archery Range); attack, accuracy (University); creation speed (Castle); more resistant to Monks (Monastery).",
"Leitis" : "Lithuanian unique cavalry unit with attack that ignores armor. Strong vs. armored units. Upgrades: attack, armor (Blacksmith); speed, hit points (Stable); creation speed, to Elite Leitis 750F, 750G (Castle); more resistant to Monks (Monastery).",
"Elite Leitis" : "Lithuanian unique cavalry unit with attack that ignores armor. Strong vs. armored units. Upgrades: attack, armor (Blacksmith); speed, hit points (Stable); creation speed (Castle); more resistant to Monks (Monastery).",
"House" : "Provides 5 population each. Your current/supportable population is shown at the top of the screen. Upgrades: line of sight (Town Center); hit points, armor (University); more resistant to Monks (Monastery).",
"Krepost" : "Fortification used to train your unique unit. Unique building of the Bulgarians. Units can garrison inside for protection. Ranged Units and Villagers shoot additional projectiles. Provides 20 population. Cannot be converted by enemy Monks. Upgrades: production speed (Castle); line of sight (Town Center); hit points, armor, accuracy (University); attack, range (Blacksmith).",
"Flaming Camel" : "Incendiary camel loaded with flammable hay and brush. Strong vs. mounted units, especially elephants. Weak vs. archers and infantry. Self-destructs when used. Upgrades: attack (University); speed, hit points (Stable); creation speed (Castle); more resistant to Monks (Monastery).",
"Trebuchet" : "Powerful anti-building siege weapon with long range. Must be packed to move, unpacked to attack. Cannot attack enemies at close range. Strong vs. buildings. Can attack ground and destroy trees. Upgrades: attack, range (University); creation speed (Castle); more resistant to Monks (Monastery).",
"Urumi Swordsman" : "Dravidian unique infantry unit which can charge its attack. Strong vs. buildings and infantry. Weak vs. archers at long range. Upgrades: attack, armor (Blacksmith); speed (Barracks); creation speed, to Elite Urumi Swordsman 900F, 450G (Castle); more resistant to Monks (Monastery).",
"Pikeman" : "Anti-cavalry infantry unit. Strong vs. mounted units, especially elephants. Weak vs. archers and infantry. Upgrades: attack, armor (Blacksmith); speed, to Halberdier 300F, 600G (Barracks); creation speed (Castle); more resistant to Monks (Monastery).",
"Halberdier" : "Anti-cavalry infantry unit. Strong vs. mounted units, especially elephants. Weak vs. archers and infantry. Upgrades: attack, armor (Blacksmith); speed (Barracks); creation speed (Castle); more resistant to Monks (Monastery).",
"Two-Handed Swordsman" : "All-purpose infantry unit. Strong vs. buildings and infantry. Weak vs. archers at long range. Upgrades: attack, armor (Blacksmith); cost, speed, to Champion 750F, 350G (Barracks); creation speed (Castle); more resistant to Monks (Monastery).",
"Heavy Cavalry Archer" : "Mounted archer. Strong vs. slow units at long range. Weak vs. Elite Skirmishers and units at close range. Upgrades: attack, range, armor (Blacksmith); accuracy, armor (Archery Range); attack, accuracy (University); speed, hit points (Stable); creation speed (Castle); more resistant to Monks (Monastery).",
"Elite Urumi Swordsman" : "Dravidian unique infantry unit which can charge its attack. Strong vs. buildings and infantry. Weak vs. archers at long range. Upgrades: attack, armor (Blacksmith); speed (Barracks); creation speed (Castle); more resistant to Monks (Monastery).",
"Camel Rider" : "Fast anti-cavalry unit. Strong vs. cavalry. Weak vs. Spearmen, Monks, and archers. Upgrades: attack, armor (Blacksmith); speed, to Heavy Camel Rider 325F, 360G (Stable); creation speed (Castle); more resistant to Monks (Monastery).",
"Heavy Camel Rider" : "Fast anti-cavalry unit. Strong vs. cavalry. Weak vs. Pikemen, Monks, and archers. Upgrades: attack, armor (Blacksmith); speed, hit points, to Imperial Camel Rider 1000F, 500G  (Stable); creation speed (Castle); more resistant to Monks (Monastery).",
"Arbalester" : "Ranged unit. Strong vs. units at long range. Weak vs. Elite Skirmishers, Onagers, and units at close range. Upgrades: attack, range, armor (Blacksmith); accuracy (Archery Range); attack, accuracy (University); creation speed (Castle); more resistant to Monks (Monastery).",
"Imperial Camel Rider" : "Indian unique anti-cavalry unit. Fast-moving. Strong vs. cavalry. Weak vs. Pikemen, Monks, and archers. Upgrades: attack, armor (Blacksmith); speed, hit points (Stable); creation speed (Castle); more resistant to Monks (Monastery).",
"Chakram Thrower" : "Gurjara unique infantry unit with ranged melee attack. Strong vs. infantry. Weak vs. archers and siege weapons.  Upgrades: attack, armor (Blacksmith); speed (Barracks); creation speed, to Elite Chakram Thrower 1000F, 650G (Castle); more resistant to Monks (Monastery).",
"Demolition Ship" : "Demolition ship armed with explosives. Strong vs. Fire Ships and buildings. Self-destructs when used. Upgrades: armor, speed, cost, to Heavy Demolition Ship 200W, 300G (Dock); more resistant to Monks (Monastery).",
"Heavy Demolition Ship" : "Demolition ship armed with explosives. Strong vs. Fire Ships and buildings. Self-destructs when used. Upgrades: armor, speed, cost (Dock); more resistant to Monks (Monastery).",
"Fire Ship" : "Warship that spews fire at close range. Strong vs. War Galleys. Weak vs. Demolition Ships. Upgrades: armor, speed, cost, to Fast Fire Ship 280W, 250G (Dock); more resistant to Monks (Monastery).",
"Elite Chakram Thrower" : "Gurjara unique infantry unit with ranged melee attack. Strong vs. infantry. Weak vs. archers and siege weapons.  Upgrades: attack, armor (Blacksmith); speed (Barracks); creation speed (Castle); more resistant to Monks (Monastery).",
"Armored Elephant" : "Anti-building cavalry unit. Resistant to most ranged attacks. Weak vs. melee units. Cannot be converted by enemy Monks from distance. Upgrades: attack, armor (Blacksmith); speed, hit points (Stable); to Siege Elephant 650F (Siege Workshop); creation speed (Castle); more resistant to Monks (Monastery).",
"Fast Fire Ship" : "Warship that spews fire at close range. Strong vs. War Galleys. Weak vs. Demolition Ships. Upgrades: armor, speed, cost (Dock); more resistant to Monks (Monastery).",
"Siege Elephant" : "Anti-building cavalry unit. Resistant to most ranged attacks. Weak vs. melee units. Cannot be converted by enemy Monks from distance. Upgrades: attack, armor (Blacksmith); speed, hit points (Stable); creation speed (Castle); more resistant to Monks (Monastery).",
"Ghulam" : "Hindustani unique infantry unit that thrusts its spear through multiple targets. Strong vs. archers. Weak vs. cavalry.  Upgrades: attack, armor (Blacksmith); speed (Barracks); creation speed, to Elite Ghulam 950F, 575G (Castle); more resistant to Monks (Monastery).",
"Elite Ghulam" : "Hindustani unique infantry unit that thrusts its spear through multiple targets. Strong vs. archers. Weak vs. cavalry.  Upgrades: attack, armor (Blacksmith); speed (Barracks); creation speed (Castle); more resistant to Monks (Monastery).",
"Thirisadai" : "Dravidian unique warship that fires multiple projectiles. Strong vs. warships. Upgrades: armor, speed, cost (Dock); more resistant to Monks (Monastery).",
"Galley" : "All-purpose warship with ranged attack. Weak vs. Fire Galleys. Upgrades: armor, speed, cost, to War Galley 230F, 100G (Dock); attack, range (Blacksmith); attack, accuracy (University); more resistant to Monks (Monastery).",
"Shrivamsha Rider" : "Gurjara unique light cavalry unit which can dodge projectiles. Strong vs. archers. Weak vs. Pikemen and Camel Riders. Upgrades: attack, armor (Blacksmith); speed, hit points, to Elite Shrivamsha Rider 850F, 500G (Stable); creation speed (Castle); more resistant to Monks (Monastery).",
"Elite Shrivamsha Rider" : "Gurjara unique light cavalry unit which can dodge projectiles. Strong vs. archers. Weak vs. Pikemen and Camel Riders. Upgrades: attack, armor (Blacksmith); speed, hit points (Stable); creation speed (Castle); more resistant to Monks (Monastery).",
"Heavy Scorpion" : "Anti-unit siege weapon. Fires bolts that pierce multiple units. Strong vs. large groups of units. Weak vs. cavalry and siege weapons. Upgrades: attack, range (University); more resistant to Monks (Monastery).",
"Caravanserai" : "Economic building. Heals and increases speed of Trade Carts in a 10 tile radius. Unique building of the Hindustanis. Upgrades: line of sight (Town Center); hit points, armor (University).",
"Camel Scout" : "Gurjara unique scout unit. Strong vs. cavalry. Weak vs. Pikemen, Monks, and archers. Upgrades: attack, armor (Blacksmith); speed, hit points (Stable); creation speed (Castle); more resistant to Monks (Monastery).",
"Transport Ship" : "Used to move units across water. Select the units you want to transport, then right-click on the Transport Ship to board them. Use the Unload button to unload units on the shore. Upgrades: armor, speed, cost, capacity (Dock); more resistant to Monks (Monastery).",
"Light Cavalry" : "Fast cavalry for scouting and raiding. Resistant to conversion. Strong vs. Monks. Weak vs. Pikemen and Camel Riders. Upgrades: attack, armor (Blacksmith); speed, hit points, to Hussar 500F, 600G or Winged Hussar 600F, 800G (Stable); more resistant to Monks (Monastery).",
"Siege Tower" : "Quick land transport used to unload units over enemy walls. Resistant to archer attack. Cannot be used by mounted units. Upgrades: more resistant to Monks (Monastery).",
"Siege Ram" : "Anti-building siege weapon. Resistant to most ranged attacks. Garrisoned infantry increase speed and attack. Upgrades: attack (University); more resistant to Monks (Monastery).",
"Boyar" : "Slavic unique cavalry unit. Resistant to melee attack. Upgrades: attack, armor (Blacksmith); speed, hit points (Stable); creation speed, to Elite Boyar 1000F, 600G (Castle); more resistant to Monks (Monastery). ",
"Onager" : "Ranged siege weapon with area of effect attack, but cannot attack enemies at close range. Strong vs. tight groups of units. Can attack ground and destroy trees. Upgrades: attack, range (University); to Siege Onager 1450F, 1000G (Siege Workshop); more resistant to Monks (Monastery).",
"Elite Boyar" : "Slavic unique cavalry unit. Resistant to melee attack. Upgrades: attack, armor (Blacksmith); speed, hit points (Stable); more resistant to Monks (Monastery).",
"Elite Cataphract" : "Byzantine unique cavalry unit. Strong vs. infantry. Weak vs. archers. Upgrades: attack, armor (Blacksmith); speed, hit points (Stable); creation speed (Castle); more resistant to Monks (Monastery).",
"Elite Chu Ko Nu" : "Chinese unique archer with rapid-fire attack. Strong vs. infantry. Weak vs. archers and siege weapons. Upgrades: attack, range, armor (Blacksmith); accuracy (Archery Range); attack, accuracy (University); creation speed (Castle); more resistant to Monks (Monastery).",
"Elite Mameluke" : "Saracen unique camel unit with ranged melee attack. Strong vs. cavalry. Weak vs. archers. Upgrades: attack, armor (Blacksmith); speed, hit points (Stable); creation speed (Castle); more resistant to Monks (Monastery).",
"Elite Huskarl" : "Gothic unique infantry unit with high pierce armor. Strong vs. archers and buildings. Weak vs. cavalry. Upgrades: attack, armor (Blacksmith); speed (Barracks); creation speed (Castle); more resistant to Monks (Monastery).",
"Elite Janissary" : "Turkish unique hand cannoneer with longer range and no minimum range. Strong vs. infantry. Weak vs. archers. Upgrades: armor (Blacksmith); creation speed (Castle); more resistant to Monks (Monastery).",
"Elite Longbowman" : "British unique archer with very long range. Strong vs. infantry. Weak vs. cavalry and Skirmishers. Upgrades: attack, range, armor (Blacksmith); attack, accuracy (University); creation speed (Castle); more resistant to Monks (Monastery).",
"Elite Longboat" : "Viking unique ship that fires multiple arrows. Strong vs. War Galleys, land units, and buildings. Upgrades: armor, speed, cost (Dock); attack, range (Blacksmith); attack, accuracy (University); more resistant to Monks (Monastery).",
"Elite Mangudai" : "Mongol unique cavalry archer with fast-firing attack. Strong vs. siege weapons and infantry. Weak vs. Skirmishers, Pikemen, and Camel Riders. Upgrades: attack, armor (Blacksmith); speed, hit points (Stable); accuracy, armor (Archery Range); attack, accuracy (University); creation speed (Castle); more resistant to Monks (Monastery).",
"Elite War Elephant" : "Persian unique unit. Slow and powerful cavalry. Strong vs. buildings and units at close range. Weak vs. Monks. Upgrades: attack, armor (Blacksmith); speed, hit points (Stable); creation speed (Castle); more resistant to Monks (Monastery).",
"Elite Samurai" : "Japanese unique infantry unit with fast attack. Strong vs. unique units and infantry. Weak vs. archers. Upgrades: attack, armor (Blacksmith); speed (Barracks); creation speed (Castle); more resistant to Monks (Monastery).",
"Elite Throwing Axeman" : "Frankish unique infantry unit with ranged melee attack. Strong vs. infantry. Weak vs. archers and siege weapons. Upgrades: attack, armor (Blacksmith); speed (Barracks); creation speed (Castle); more resistant to Monks (Monastery).",
"Elite Teutonic Knight" : "Teutonic unique infantry unit. Slow and powerful. Strong vs. melee units. Weak vs. archers and Scorpions. Upgrades: attack, armor (Blacksmith); speed (Barracks); creation speed (Castle); more resistant to Monks (Monastery).",
"Elite Woad Raider" : "Celtic unique infantry unit. Fast-moving. Strong vs. infantry and siege weapons. Weak vs. archers and cavalry. Upgrades: attack, armor (Blacksmith); speed (Barracks); creation speed (Castle); more resistant to Monks (Monastery).",
"Lumber Camp" : "Used to deposit wood and research wood-gathering technologies. Build near forests to gather wood faster.  Upgrades: line of sight (Town Center); hit points, armor (University); more resistant to Monks (Monastery).",
"Champion" : "All-purpose infantry unit. Strong vs. buildings and infantry. Weak vs. archers at long range. Upgrades: attack, armor (Blacksmith); cost, speed (Barracks); creation speed (Castle); more resistant to Monks (Monastery).",
"Paladin" : "Powerful all-purpose cavalry. Strong vs. infantry and archers. Weak vs. Halberdiers, Heavy Camel Riders, and Monks. Upgrades: attack, armor (Blacksmith); speed, hit points (Stable); more resistant to Monks (Monastery).",
"Mining Camp" : "Used to deposit stone and gold and research mining technologies. Build near stone or gold mines to gather these resources faster. Upgrades: line of sight (Town Center); hit points, armor (University); more resistant to Monks (Monastery).",
"Siege Onager" : "Ranged siege weapon with area of effect attack, but cannot attack enemies at close range. Strong vs. tight groups of units. Can attack ground and destroy trees. Upgrades: attack, range (University); more resistant to Monks (Monastery).",
"Fish Trap" : "Renewable food source, similar to a farm but built by Fishing Ships. Provides a limited amount of food before it collapses and must be rebuilt. Cannot be converted by enemy Monks. Upgrades: line of sight (Town Center); hit points (University).",
"Outpost" : "Watch tower with great line-of-sight to discover nearby enemy activity. Does not attack and cannot garrison units inside. Upgrades: line of sight (Town Center); hit points, armor (University); more resistant to Monks (Monastery).",
"Coustillier" : "Burgundian unique cavalry unit which can charge its attack. Strong vs. infantry and archers. Weak vs. Camel Riders and Monks. Upgrades: attack, armor (Blacksmith); speed, hit points (Stable); creation speed, to Elite Coustillier 1000F, 800G (Castle); more resistant to Monks (Monastery).",
"Elite Coustillier" : "Burgundian unique cavalry unit which can charge its attack. Strong vs. infantry and archers. Weak vs. Camel Riders and Monks. Upgrades: attack, armor (Blacksmith); speed, hit points (Stable); creation speed (Castle); more resistant to Monks (Monastery).",
"Serjeant" : "Sicilian unique infantry unit which can construct Donjons. Upgrades: attack, armor (Blacksmith); speed (Barracks); creation speed, to Elite Serjeant 1100F, 800G (Castle); more resistant to Monks (Monastery).",
"Elite Serjeant" : "Sicilian unique infantry unit which can construct Donjons. Upgrades: attack, armor (Blacksmith); speed (Barracks); creation speed (Castle); more resistant to Monks (Monastery).",
"Flemish Militia" : "Burgundian unique infantry unit. Strong vs. cavalry. Weak vs. archers. Upgrades: attack, armor (Blacksmith); speed (Barracks); more resistant to Monks (Monastery).",
"Donjon" : "Fortification used to train your unique unit. Unique building of the Sicilians. Units can garrison inside for protection. Ranged Units and Villagers shoot additional projectiles. Upgrades: production speed (Castle); line of sight (Town Center); hit points, armor, accuracy (University); attack, range (Blacksmith).",
"Obuch" : "Polish unique infantry unit which can damage the armor of units it is fighting. Strong vs. buildings and infantry. Weak vs. archers at long range. Upgrades: attack, armor (Blacksmith); speed (Barracks); creation speed, to Elite Obuch 800F, 600G (Castle); more resistant to Monks (Monastery).",
"Elite Obuch" : "Polish unique infantry unit which can damage the armor of units it is fighting. Strong vs. buildings and infantry. Weak vs. archers at long range. Upgrades: attack, armor (Blacksmith); speed (Barracks); creation speed (Castle); more resistant to Monks (Monastery).",
"Hussite Wagon" : "Bohemian unique siege unit. Units behind it receive 50% less damage from incoming projectiles. Strong vs. archers. Weak vs. siege weapons. Upgrades: attack, range (University); creation speed, to Elite Hussite Wagon 800W, 600G (Castle); more resistant to Monks (Monastery).",
"Elite Hussite Wagon" : "Bohemian unique siege unit. Units behind it receive 50% less damage from incoming projectiles. Strong vs. archers. Weak vs. siege weapons. Upgrades: attack, range (University); creation speed (Castle); more resistant to Monks (Monastery).",
"Elite Cannon Galleon" : "Anti-building siege warship with long range, but cannot attack enemies at close range. Strong vs. buildings. Weak vs. other units. Upgrades: armor, speed, cost (Dock); more resistant to Monks (Monastery).",
"Berserk" : "Viking unique infantry unit that slowly heals itself. Strong vs. infantry and siege weapons. Weak vs. archers. Upgrades: attack, armor (Blacksmith); speed (Barracks); creation speed, to Elite Berserk 1075F, 475G (Castle); more resistant to Monks (Monastery).",
"Elite Berserk" :  "Viking unique infantry unit that slowly heals itself. Strong vs. infantry and siege weapons. Weak vs. archers. Upgrades: attack, armor (Blacksmith); speed (Barracks); creation speed (Castle); more resistant to Monks (Monastery).",
"Winged Hussar" : "Unique to Poles and Lithuanians. Fast cavalry for scouting and raiding. Resistant to conversion. Strong vs. Monks and gunpowder units. Weak vs. Pikemen and Camel Riders. Upgrades: attack, armor (Blacksmith); speed, hit points (Stable); more resistant to Monks (Monastery).",
"Houfnice" : "Bohemian unique siege unit. Siege weapon with long range. Strong vs. buildings and siege weapons. Weak vs. melee units. Upgrades: attack, range (University); more resistant to Monks (Monastery).",
"Folwark" : "Unique building of the Poles. Used to deposit food and research farming technologies. Immediately collects 10% of food from nearby newly constructed farms. Provides 5 population. Build near forage bushes or other source of food to gather food faster. Upgrades: line of sight (Town Center); hit points, armor (University); more resistant to Monks (Monastery).",
"Petard" : "Demolition siege unit armed with explosives. Strong vs. buildings. Weak vs. other units. Self-destructs when used. Upgrades: attack (University); creation speed (Castle); more resistant to Monks (Monastery).",
"Hussar" : "Fast cavalry for scouting and raiding. Resistant to conversion. Strong vs. Monks. Weak vs. Pikemen and Camel Riders. Upgrades: attack, armor (Blacksmith); speed, hit points (Stable); more resistant to Monks (Monastery).",
"Jaguar Warrior" : "Aztec unique infantry unit. Strong vs. infantry. Weak vs. cavalry and archers. Upgrades: attack, armor (Blacksmith); speed (Barracks); creation speed, to Elite Jaguar Warrior 1000F, 500G (Castle); more resistant to Monks (Monastery).",
"Elite Jaguar Warrior" : "Aztec unique infantry unit. Strong vs. infantry. Weak vs. cavalry and archers. Upgrades: attack, armor (Blacksmith); speed (Barracks); creation speed (Castle); more resistant to Monks (Monastery).",
"Eagle Warrior" : "Fast infantry for scouting and raiding. Resistant to conversion. Strong vs. Monks and archers. Weak vs. Long Swordsmen and cavalry. Upgrades: attack, armor (Blacksmith); speed, to Elite Eagle Warrior 800F, 500G (Barracks); creation speed (Castle); more resistant to Monks (Monastery).",
"Eagle Scout" : "Fast infantry for scouting and raiding. Resistant to conversion. Strong vs. Monks and archers. Weak vs. Men-at-Arms and cavalry. Upgrades: attack, armor (Blacksmith); speed, to Eagle Warrior 200F, 200G (Barracks); creation speed (Castle); more resistant to Monks (Monastery).",
"Elite Eagle Warrior" : "Fast infantry for scouting and raiding. Resistant to conversion. Strong vs. Monks and archers. Weak vs. Long Swordsmen and cavalry. Upgrades: attack, armor (Blacksmith); speed (Barracks); creation speed (Castle); more resistant to Monks (Monastery).",
"Tarkan" : "Hunnic unique cavalry unit with attack bonus vs. buildings. Strong vs. buildings and archers. Weak vs. Pikemen and Camel Riders. Upgrades: attack, armor (Blacksmith); speed, hit points (Stable); creation speed, to Elite Tarkan 1000F, 500G (Castle); more resistant to Monks (Monastery).",
"Elite Tarkan" : "Hunnic unique cavalry unit with attack bonus vs. buildings. Strong vs. buildings and archers. Weak vs. Pikemen and Camel Riders. Upgrades: attack, armor (Blacksmith); speed, hit points (Stable); creation speed (Castle); more resistant to Monks (Monastery).",
"Elephant Archer" : "Slow and heavy mounted archer. Strong vs. archers and infantry. Weak vs. Pikemen, Skirmishers, and Camel Riders. Upgrades: attack, range, armor (Blacksmith); speed, hit points (Stable); accuracy, to Elite Elephant Archer 1000F, 800G (Archery Range); attack, accuracy (University); creation speed (Castle); more resistant to Monks (Monastery).",
"Plumed Archer" : "Mayan unique fast-moving archer. Strong vs. archers and infantry. Weak vs. cavalry. Upgrades: attack, range, armor (Blacksmith); accuracy (Archery Range); attack, accuracy (University); creation speed, to Elite Plumed Archer 700F, 1000W (Castle); more resistant to Monks (Monastery).",
"Elite Elephant Archer" : "Slow and heavy mounted archer. Strong vs. archers and infantry. Weak vs. Pikemen, Skirmishers, and Camel Riders. Upgrades: attack, range, armor (Blacksmith); speed, hit points (Stable); accuracy (Archery Range); attack, accuracy (University); creation speed (Castle); more resistant to Monks (Monastery).",
"Elite Plumed Archer" : "Mayan unique fast-moving archer. Strong vs. archers and infantry. Weak vs. cavalry. Upgrades: attack, range, armor (Blacksmith); accuracy (Archery Range); attack, accuracy (University); creation speed (Castle); more resistant to Monks (Monastery).",
"Kamayuk" : "Inca unique spearman with increased attack range. Strong vs. cavalry and infantry. Weak vs. archers. Upgrades: attack, armor (Blacksmith); speed (Barracks); creation speed, to Elite Kamayuk 900F, 500G  (Castle); more resistant to Monks (Monastery).",
"Conquistador" : "Spanish unique mounted hand cannoneer. Strong vs. infantry. Weak vs. Pikemen, Skirmishers, and Monks. Upgrades: armor (Blacksmith); speed, hit points (Stable); creation speed, to Elite Conquistador 1200F, 600G (Castle); more resistant to Monks (Monastery).",
"Elite Kamayuk" : "Inca unique spearman with increased attack range. Strong vs. cavalry and infantry. Weak vs. archers. Upgrades: attack, armor (Blacksmith); speed (Barracks); creation speed (Castle); more resistant to Monks (Monastery).",
"Elite Conquistador" : "Spanish unique mounted hand cannoneer. Strong vs. infantry. Weak vs. Pikemen, Skirmishers, and Monks. Upgrades: armor (Blacksmith); speed, hit points (Stable); creation speed (Castle); more resistant to Monks (Monastery).",
"Slinger" : "Inca unique unit. Ranged anti-infantry unit that cannot attack at close range. Strong vs. infantry. Weak vs. archers and cavalry. Upgrades: attack, range, armor (Blacksmith); accuracy (Archery Range); attack, accuracy (University); creation speed (Castle); more resistant to Monks (Monastery).",
"Missionary" : "Spanish unique mounted monk. Converts enemy units and heals friendly units. Faster than Monk but with less sight and range. Strong vs. slow, non-ranged units. Weak vs. Light Cavalry and ranged units. Cannot collect Relics. Upgrades: at Monastery; speed, hit points (Stable).",
"Genoese Crossbowman" : "Italian unique archer. Strong vs. cavalry and infantry. Weak vs. archers and siege weapons. Upgrades: attack, range, armor (Blacksmith); accuracy (Archery Range); attack, accuracy (University); creation speed, to Elite Genoese Crossbowman 900F, 750G (Castle); more resistant to Monks (Monastery).",
"Elite Genoese Crossbowman" : "Italian unique archer. Strong vs. cavalry and infantry. Weak vs. archers and siege weapons. Upgrades: attack, range, armor (Blacksmith); accuracy (Archery Range); attack, accuracy (University); creation speed (Castle); more resistant to Monks (Monastery).",
"War Wagon" : "Korean unique cavalry archer unit. Strong vs. infantry and archers. Weak vs. Pikemen, Skirmishers, and Camel Riders. Upgrades: attack, range, armor (Blacksmith); speed (Stable); accuracy (Archery Range); attack, accuracy (University); creation speed, to Elite War Wagon 1000W, 800G (Castle); more resistant to Monks (Monastery).",
"Magyar Huszar" : "Magyar unique light cavalry unit. Strong vs. siege weapons. Weak vs. Pikemen and Camel Riders. Upgrades: attack, armor (Blacksmith); speed, hit points (Stable); creation speed, to Elite Magyar Huszar 800F, 600G (Castle); more resistant to Monks (Monastery).",
"Elite War Wagon" : "Korean unique cavalry archer unit. Strong vs. infantry and archers. Weak vs. Pikemen, Skirmishers, and Camel Riders. Upgrades: attack, range, armor (Blacksmith); speed (Stable); accuracy (Archery Range); attack, accuracy (University); creation speed (Castle); more resistant to Monks (Monastery).",
"Elite Magyar Huszar" : "Magyar unique light cavalry unit. Strong vs. siege weapons. Weak vs. Pikemen and Camel Riders. Upgrades: attack, armor (Blacksmith); speed, hit points (Stable); creation speed (Castle); more resistant to Monks (Monastery).",
"Turtle Ship" : "Korean unique ship. Slow and ironclad. Strong vs. warships and buildings. Upgrades: armor, speed, cost, to Elite Turtle Ship 1000F, 800G (Dock); more resistant to Monks (Monastery).",
"Elite Turtle Ship" : "Korean unique ship. Slow and ironclad. Strong vs. warships and buildings. Upgrades: armor, speed, cost (Dock); more resistant to Monks (Monastery).",
"Town Watch" : " Increases the line of sight of all buildings by +4 so they see enemies from a longer distance.",
"Crop Rotation" : " Farms produce +175 food so they last longer before you must rebuild them.",
"Heavy Plow" : " Farms produce +125 food so they last longer before you must rebuild them. Farmers carry +1 food each trip.",
"Horse Collar" : " Farms produce +75 food so they last longer before you must rebuild them.",
"Guilds" : " Reduces the commodity trading fee to 15%.",
"Banking" : " Tributes are free.",
"Cartography" : " You and your allies share the same line of sight (you see what they see).",
"Loom" : " Makes your villagers harder to kill by providing +15 hit points and +1 normal/+2 pierce armor.",
"Coinage" : " Reduces fee for tributes to 20%.",
"Husbandry" : " Cavalry move 10% faster.",
"Faith" : " Units are 50% harder for enemy Monks to convert.",
"Chemistry" : " Missile units (except gunpowder units) have +1 attack strength.<b>Required for<br>\ngunpowder units (Hand Cannoneer, Cannon Galleon, Bombard Cannon,<br>\nBombard Tower).</b></i>",
"Masonry" : " Strengthens all buildings by providing 10% more hit points, +1 normal/+1 pierce armor, and +3 building armor.",
"Architecture" : " Strengthens all buildings by providing 10% more hit points, +1 normal/+1 pierce armor, and +3 building armor.",
"Treadmill Crane" : " Villagers construct buildings 20% faster.",
"Gold Mining" : " Villagers mine gold 15% faster.",
"Kataparuto" : " Trebuchets fire and pack/unpack faster.",
"Keep" : " Upgrades Guard Towers and lets you build Keeps, which are stronger and have more attack strength, range, and armor.",
"Forging" : " Infantry and cavalry have +1 attack.",
"Iron Casting" : " Infantry and cavalry have +1 attack.",
"Scale Mail Armor" : " Infantry have +1 normal/+1 pierce armor.",
"Blast Furnace" : " Infantry and cavalry have +2 attack.",
"Chain Mail Armor" : " Infantry have +1 normal/+1 pierce armor.",
"Plate Mail Armor" : " Infantry have +1 normal/+2 pierce armor.",
"Plate Barding Armor" : " Cavalry have +1 normal/+2 pierce armor.",
"Scale Barding Armor" : " Cavalry have +1 normal/+1 pierce armor.",
"Chain Barding Armor" : " Cavalry have +1 normal/+1 pierce armor.",
"Tracking" : " Infantry have +2 line of sight so they see enemy units from a longer distance.",
"Ballistics" : " Archers, Town Centers, Castles, Galleys, Unique Naval Units, and Mounted Archers fire more accurately at moving targets.",
"Feudal Age" : "Improves your civilization. Gives you access to different buildings, more powerful military units, and stronger technologies. Before you can advance, you must have any two Dark Age buildings: Lumber Camp, Mining Camp, Mill, Dock, or Barracks.",
"Castle Age" : "Improves your civilization. Gives you access to different buildings, more powerful military units, and stronger technologies. Before you can advance, you must have any two Feudal Age buildings: Archery Range, Stable, Blacksmith, or Market.",
"Imperial Age" : "Improves your civilization. Gives you access to different buildings, more powerful military units, and stronger technologies. Before you can advance, you must have a Castle/Krepost or any two Castle Age buildings: University, Siege Workshop, or Monastery.",
"Bodkin Arrow" : " Archers, cavalry archers, galleys, Castles, and towers have +1 attack and +1 range. Town Centers have +1 attack.",
"Bracer" : " Archers, cavalry archers, galleys, Castles, and towers have +1 attack and +1 range. Town Centers have +1 attack.",
"Fortified Wall" : " Upgrades your Stone Walls and lets you build Fortified Walls, which are stronger and harder to breach. Also increases the hit points of your Gates, which makes them harder to destroy.",
"Fletching" : " Archers, cavalry archers, galleys, Castles, and towers have +1 attack and +1 range. Town Centers have +1 attack.",
"Gold Shaft Mining" : " Villagers mine gold 15% faster.",
"Guard Tower" : " Upgrades your Watch Towers and lets you build Guard Towers, which are stronger and have more attack strength.",
"Double-Bit Axe" : " Villagers chop wood 20% faster.",
"Bow Saw" : " Villagers chop wood 20% faster.",
"Padded Archer Armor" : " Archers and cavalry archers have +1 normal/+1 pierce armor.",
"Leather Archer Armor" : " Archers and cavalry archers have +1 normal/+1 pierce armor.",
"Squires" : " Infantry move 10% faster.",
"Wheelbarrow" : " Villagers work more efficiently by moving 10% faster and carrying 25% more resources.",
"Ring Archer Armor" : " Archers and cavalry archers have +1 normal/+2 pierce armor.",
"Illumination" : " Monks regain their faith 50% faster after a successful conversion.",
"Sanctity" : " Monks have +15 hit points so they are harder to kill.",
"Block Printing" : " Monks have +3 conversion range.",
"Two-Man Saw" : " Villagers chop wood 10% faster.",
"Hand Cart" : " Villagers work more efficiently by moving 10% faster and carrying 50% more resources.",
"Fervor" : " Monks move 15% faster.",
"Carrack" : " Ships receive +1 normal/+1 pierce armor.",
"Arquebus" : " Ballistics for gunpowder units.",
"Royal Heirs" : " Shotel Warriors are created nearly instantly.",
"Torsion Engines" : " Siege workshop units blast radius increased.",
"Tigui" : " Town Centers fire arrows.",
"Farimba" : " Cavalry +5 attack.",
"Kasbah" : " Team castles work 25% faster.",
"Maghrebi Camels" : " Camel units regenerate.",
"Arson" : " Infantry do more damage vs. buildings.",
"Andean Sling" : " Upgrades your skirmishers and slingers by removing their minimum range.",
"Fabric Shields" : " Kamayuks, Slingers, Eagles have +1 armor/+2 pierce armor.",
"Druzhina" : " Infantry damage adjacent units.",
"Grand Trunk Road" : " All gold income 10% faster (Trade, mines, relics).",
"Shatagni" : " Hand cannoneers have +2 range.",
"Pavise" : " Foot Archers and Condottieri have +1 armor/+1 pierce armor.",
"Silk Road" : " Trade units cost -50%.",
"Recurve Bow" : " Cavalry archers have +1 range, +1 attack.",
"Corvinian Army" : " Magyar Huszars cost no gold.",
"Stone Mining" : " Villagers mine stone 15% faster.",
"Stone Shaft Mining" : " Villagers mine stone 15% faster.",
"Arrowslits" : " Increases the attack of towers and Donjons.",
"Nomads" : " Houses don't lose their population room when they are destroyed.",
"Kamandaran" : " Archer-line gold cost is replaced by additional wood cost.",
"Town Patrol" : " Increases the line of sight of all buildings by +4 so they see enemies from a longer distance.",
"Ironclad" : " Increases the armor of all siege weapons so they're more resistant to melee attack.",
"Sipahi" : " Cavalry archers have +20 hit points.",
"Inquisition" : " Increases monk conversion rate.",
"Chivalry" : " Increases the production speed of stables by +40%.",
"Tusk Swords" : " Battle Elephants receive +3 attack",
"Double Crossbows" : " Ballista Elephants and Scorpions fire two projectiles.",
"Thalassocracy" : " Upgrades your Docks to Harbors, which fire arrows.",
"Forced Levy" : " Militia-line gold cost is replaced by additional food cost.",
"Howdah" : " Battle Elephants receive +1 normal/+1 pierce armor.",
"Manipur Cavalry" : " Cavalry deals +5 bonus attack vs. archers.",
"Chatras" : " Battle Elephants receive +100 HP.",
"Paper Money" : " Lumberjacks slowly generate gold in addition to wood.",
"Stirrups" : " Cavalry attack 33% faster.",
"Bagains" : " Militia-line receives +5 melee armor.",
"Silk Armor" : " Light Cavalry, Steppe Lancers and Cavalry Archers receive +1 normal/+1 pierce armor.",
"Timurid Siegecraft" : " Trebuchets receive +2 range. Enables Flaming Camels.",
"Steppe Husbandry" : " Light Cavalry, Steppe Lancers and Cavalry Archers trained 100% faster.",
"Chieftains" : " Infantry get attack bonus vs. cavalry.",
"Greek Fire" : " Fire Ships have +1 range.",
"Gillnets" : " Fishing Ships gather 25% faster.",
"Redemption" : " Monks can convert enemy buildings (except Town Centers, Castles, Monasteries, Farms, Fish Traps, walls, Gates, and Wonders) and siege weapons. Monks can convert most enemy units from a distance, but they must stand adjacent to buildings, rams, and Trebuchets to convert them.",
"Atonement" : " Monks can convert enemy Monks.",
"Logistica" : " Cataphracts cause trample damage.",
"Conscription" : " Military buildings (except Siege Workshops) work 33% faster.",
"Bombard Tower" : " Lets you build Bombard Towers, which are powerful and have extensive line of sight.",
"Murder Holes" : " Eliminates the minimum range of all towers, Castles and Harbors so they can fire at enemies attacking their base.",
"Sappers" : " Villagers cause +15 damage when attacking buildings.",
"Bearded Axe" : " Throwing Axemen have +1 range.",
"Supremacy" : " Villagers have exceptional combat abilities.",
"Atlatl" : " Skirmishers have +1 attack, +1 range.",
"Warwolf" : " Improves your Trebuchets by giving them blast damage.",
"Burgundian Vineyards" : " Farmers slowly generate gold in addition to food.",
"Flemish Revolution" : " Upgrades all existing Villagers to Flemish Militia and allows Flemish Militia to be created at the Town Center.",
"First Crusade" : " Each Town Center (maximum 5) spawns a one-time batch of 7 Serjeants. Units more resistant to conversion.",
"Hauberk" : " Knights receive +1 normal/+2 pierce armor.",
"Szlachta Privileges" : " Knights cost -60% gold.",
"Lechitic Legacy" : " Light Cavalry deals trample damage.",
"Wagenburg Tactics" : " Gunpowder units move 15% faster.",
"Hussite Reforms" : " Monks and Monastery technologies have their gold cost replaced by food.",
"Medical Corps" : " Elephant units regenerate 20 HP per minute.",
"Wootz Steel" : " Infantry and cavalry attacks ignore armor.",
"Paiks" : " Rathas and elephant units attack 20% faster.",
"Mahayana" : " Villagers take 10% less population space.",
"Kshatriyas" : " Military units cost -25% food.",
"Frontier Guards" : " Camel Riders and Elephant Archers receive +4 melee armor.",
"Great Wall" : " Makes your walls and towers stronger by giving them +30% hit points.",
"Stronghold" : " Makes your castles and towers stronger by making them fire 25% faster.",
"Marauders" : " Enables you to create Tarkans at Stables.",
"Yasama" : " Makes your towers stronger by making them shoot extra arrows.",
"Careening" : " Makes ships less vulnerable to missile attack with +1 pierce armor. Transport Ships carry +5 units.",
"Dry Dock" : " Ships move 15% faster. Transport Ships carry +10 units.",
"Heated Shot" : " Towers cause 125% more damage to ships; Castles cause 25% more damage to ships.",
"Hoardings" : " Strengthens Castles by providing +20% hit points.",
"Shipwright" : " Ships cost 20% less wood; build 35% faster.",
"Siege Engineers" : " Siege weapons have +1 range (except rams) and cause 20% more damage to buildings (40% more for Petards).",
"Hul'che Javelineers" : " Improves your Skirmishers by making them throw a second projectile.",
"Eupseong" : " Watch Towers, Guard Towers and Keeps have +2 range.",
"Cuman Mercenaries" : " Team members can create 5 free Elite Kipchaks per Castle.",
"Hill Forts" : " Town Centers receive +3 range.",
"Tower Shields" : " Pikemen and Skirmishers receive +2 pierce armor.",
"Supplies" : " Militia-line costs -15 food.",
"Spies/Treason" : "Spies (Random Map) Reveals all enemy units and buildings by showing you their line of sight. The total cost is 200 gold per each villager from other players; allied villagers are excluded when teams are locked. Treason (Regicide games) reveals the position of all enemy Kings to your team for a few seconds. The Kings appear on the mini-map as a flashing X. Each time you choose Treason, 400 gold is immediately deducted from your stockpile.",
"Bloodlines" : " Mounted units have +20 hit points.",
"Caravan" : " Trade Carts and Trade Cogs move 50% faster (so gold accumulates faster).",
"Thumb Ring" : " Archers fire faster and with 100% accuracy.",
"Heresy" : " Units converted by an enemy Monk (or Missionary) die instead of changing to the enemy's color.",
"Parthian Tactics" : " Mounted Archers have +1 normal/+2 pierce armor; Cavalry Archers have +4, Unique Mounted Archers +2 attack vs. pikemen.",
"Theocracy" : " If a group of Monks converts an enemy unit, only one of the Monks must rest afterward.",
"Yeomen" : " Foot archers have +1 range; towers have +2 attack.",
"El Dorado" : " Eagle Warriors have +40 hit points.",
"Furor Celtica" : " Siege Workshop units have +40% hit points.",
"Drill" : " Siege Workshop units move 50% faster.",
"Mahouts" : " War Elephants move 30% faster.",
"Zealotry" : " Camel units have +20 hit points.",
"Artillery" : " Bombard Towers, Bombard Cannons, and Cannon Galleons have +2 range.",
"Crenellations" : " Castles have +3 range; garrisoned infantry fire arrows.",
"Anarchy" : " Allows Huskarls to be created at the Barracks.",
"Atheism" : " Relic and Wonder victories take +100 years to complete; enemy relics generate -50% resources.",
"Garland Wars" : " Infantry have +4 attack.",
"Berserkergang" : " Berserks regenerate faster.",
"Rocketry" : " Chu Ko Nu have +2 piercing attack; scorpions have +4 piercing attack.",
"Herbal Medicine" : " Units garrisoned in buildings heal 6X faster.",
"Shinkichon" : " Mangonels, Onagers, and Siege Onagers have +1 range.",
"Perfusion" : " Barracks units are created 100% faster.",
"Counterweights" : " Trebuchets and Mangonel-line +15% attack.",
"Detinets" : " Replaces 40% of Castles' and Towers' stone cost with wood.",
"Konnik" : " Bulgarian unique cavalry unit that fights on as infantry when felled. Strong vs. infantry and archers. Weak vs. Camel Riders and Monks.Upgrades: attack, armor (Blacksmith); speed, hit points (Stable); creation speed, to Elite Konnik 1000F, 750G (Castle); more resistant to Monks (Monastery). ‹attack› ‹armor› ‹piercearmor› ‹range›",
"Elite Konnik" : " Bulgarian unique cavalry unit that fights on as infantry when felled. Strong vs. infantry and archers. Weak vs. Camel Riders and Monks.Upgrades: attack, armor (Blacksmith); speed, hit points (Stable); creation speed (Castle); more resistant to Monks (Monastery). ‹attack› ‹armor› ‹piercearmor› ‹range›",
"Ratha" : " Bengali unique chariot that can switch between melee and ranged attacks. Strong vs. infantry. Weak vs. Skirmishers and Camel Riders.Upgrades: attack, armor (Blacksmith); speed, hit points (Stable); creation speed, to Elite Ratha 800F, 800W (Castle); more resistant to Monks (Monastery). ‹attack› ‹armor› ‹piercearmor› ‹range›",
"Elite Ratha" : " Bengali unique chariot that can switch between melee and ranged attacks. Strong vs. infantry. Weak vs. Skirmishers and Camel Riders.Upgrades: attack, armor (Blacksmith); speed, hit points (Stable); creation speed (Castle); more resistant to Monks (Monastery). ‹attack› ‹armor› ‹piercearmor› ‹range›",
"Ratha" : " Bengali unique chariot that can switch between melee and ranged attacks. Strong vs. infantry. Weak vs. Skirmishers and Camel Riders.Upgrades: attack, armor (Blacksmith); speed, hit points (Stable); creation speed, to Elite Ratha 800F, 800W (Castle); more resistant to Monks (Monastery). ‹attack› ‹armor› ‹piercearmor› ‹range›",
"Elite Ratha" : " Bengali unique chariot that can switch between melee and ranged attacks. Strong vs. infantry. Weak vs. Skirmishers and Camel Riders.Upgrades: attack, armor (Blacksmith); speed, hit points (Stable); creation speed (Castle); more resistant to Monks (Monastery). ‹attack› ‹armor› ‹piercearmor› ‹range›",
}
